<?php

/**
 * This module offers Wincache support for Drupal, including
 * statistics gathering and cache usage control.
 */

// Check usercache usage, do that on all requests.
register_shutdown_function('wincachedrupal_shutdown_check_ucache');

/**
 * Implements hook_menu().
 */
function wincachedrupal_menu() {
  $items['admin/reports/status/wincache'] = array(
    'title' => 'Wincache',
    'page callback' => 'WincacheDrupalStatsPageCallback',
    'access arguments' => array('administer site configuration'),
    'type' => MENU_CALLBACK,
    'file' => 'wincachedrupal.inc',
  );
  return $items;
}

/**
 * Implements hook_admin_paths().
 */
function wincachedrupal_admin_paths() {
  $paths = array(
    // This page should not be treated as administrative since it outputs its
    // own content (outside of any administration theme).
    'admin/reports/status/wincache' => FALSE,
  );
  return $paths;
}

/**
 * Implements hook_permission().
 */
function wincachedrupal_permission() {
  return array(
    'access wincache statistics' => array(
      'title' => t('Access wincache statistics'),
      'description' => t('Allows access to the statistics reports of WinCache.'),
    ),
  );
}

/**
 * Shutdown function to verifiy user cache usage.
 *
 * If you run out of User cache in Wincache, the application
 * will start loosing performance at the speed of light.
 *
 */
function wincachedrupal_shutdown_check_ucache() {
  $user_cache_available = function_exists('wincache_ucache_info') && !strcmp(ini_get('wincache.ucenabled'), "1");
  if ($user_cache_available) {
    $ucache_mem_info = wincache_ucache_meminfo();
    // Under some situations WincacheDrupal will fail to report
    // any data through wincache_ucache_meminfo().
    if (empty($ucache_mem_info)) {
      // This watchdog has been commented out for performance reasons, the fact
      // that $ucache_mem_info is not working has been proved not to be an issue
      // or indicator that the overall cache is failing in any way.
      // watchdog('WincacheDrupal', 'User cache is improperly reporting memory usage statistics: @stats', array('@stats' => json_encode($ucache_mem_info)), WATCHDOG_DEBUG);
      return;
    }
    $ucache_available_memory = $ucache_mem_info['memory_total'] - $ucache_mem_info['memory_overhead'];
    $free_memory_ratio = $ucache_mem_info['memory_free'] / $ucache_available_memory;
    // If free memory is below 10% of total
    // do a cache wipe!
    if ($free_memory_ratio < 0.10) {
      $params = array();
      $params["@free"] = round($ucache_mem_info['memory_free'] / 1024, 0);
      $params["@total"] = round($ucache_mem_info['memory_total'] / 1024, 0);
      $params["@avail"] = round($ucache_available_memory / 1024, 0);
      watchdog('WincacheDrupal', 'Usercache threshold limit reached. @free Kb free out of @avail Kb available from a total of @total Kb. Cache cleared.', $params, WATCHDOG_CRITICAL);
      wincache_ucache_clear();
    }
  }
}
